<a href="https://colab.research.google.com/github/gabrielfauro-bee/Atividades_FMC2026/blob/main/Atividade_Web_Scraping_Oscar_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Web Scraping — Dados do Oscar (2010–2015)

Este notebook extrai os dados da página **Scrape This Site — AJAX and Javascript**.

## Etapa 1 — Instalar e importar as bibliotecas

- **requests**: realiza as requisições ao site;
- **pandas**: organiza os dados em tabela;
- **time**: cria uma pequena pausa entre as requisições;
- **google.colab.files**: permite baixar o Excel ao final.

In [1]:
!pip -q install openpyxl

import requests
import pandas as pd
import time

from google.colab import files

print("Bibliotecas carregadas com sucesso!")

Bibliotecas carregadas com sucesso!

## Etapa 2 — Definir a página e os anos

O exercício possui dados de **2010 a 2015**.

Será criada uma lista chamada `todos_filmes` para armazenar os registros extraídos de todos os anos.

In [2]:
url = "https://www.scrapethissite.com/pages/ajax-javascript/"

anos = range(2010, 2016)

todos_filmes = []

print("Anos que serão consultados:", list(anos))

Anos que serão consultados: [2010, 2011, 2012, 2013, 2014, 2015]

## Etapa 3 — Extrair os dados de cada ano

Para cada ano, o código envia os parâmetros:

- `ajax=true`
- `year=ANO`

A resposta é convertida de JSON para objetos Python. Em seguida, cada filme é adicionado à lista geral.

In [3]:
for ano in anos:

    print(f"Extraindo dados do Oscar de {ano}...")

    parametros = {
        "ajax": "true",
        "year": ano
    }

    resposta = requests.get(
        url,
        params=parametros,
        timeout=30
    )

    # Interrompe a execução se houver erro HTTP
    resposta.raise_for_status()

    # Converte a resposta JSON para uma estrutura Python
    filmes = resposta.json()

    for filme in filmes:

        todos_filmes.append({
            "Ano": filme.get("year", ano),
            "Filme": filme.get("title"),
            "Indicações": filme.get("nominations"),
            "Prêmios": filme.get("awards"),
            "Melhor Filme": filme.get("best_picture", False)
        })

    print(f"✓ {len(filmes)} filmes encontrados em {ano}")

    # Pequena pausa entre as consultas
    time.sleep(0.5)

print("\nExtração concluída!")
print("Total de registros extraídos:", len(todos_filmes))

Extraindo dados do Oscar de 2010...
✓ 13 filmes encontrados em 2010
Extraindo dados do Oscar de 2011...
✓ 15 filmes encontrados em 2011
Extraindo dados do Oscar de 2012...
✓ 15 filmes encontrados em 2012
Extraindo dados do Oscar de 2013...
✓ 12 filmes encontrados em 2013
Extraindo dados do Oscar de 2014...
✓ 16 filmes encontrados em 2014
Extraindo dados do Oscar de 2015...
✓ 16 filmes encontrados em 2015

Extração concluída!
Total de registros extraídos: 87

## Etapa 4 — Criar uma única tabela

Agora os registros de todos os anos serão transformados em um `DataFrame` do pandas.

As linhas serão organizadas por **Ano** e **Filme**.

In [4]:
df = pd.DataFrame(todos_filmes)

df = df.sort_values(
    by=["Ano", "Filme"],
    ascending=[True, True]
).reset_index(drop=True)

display(df)

     Ano                Filme  Indicações  Prêmios  Melhor Filme
0   2010  Alice in Wonderland           3        2         False
1   2010           Black Swan           5        1         False
2   2010          God of Love           1        1         False
3   2010    In a Better World           1        1         False
4   2010            Inception           8        4         False
..   ...                  ...         ...      ...           ...
82  2015          Stutterer             1        1         False
83  2015      The Big Short             5        1         False
84  2015      The Danish Girl           4        1         False
85  2015  The Hateful Eight             2        1         False
86  2015      The Revenant             12        3         False

[87 rows x 5 columns]

## Etapa 5 — Padronizar a coluna “Melhor Filme”

Os valores booleanos:

- `True` → **Sim**
- `False` → **Não**

serão convertidos para facilitar a leitura da tabela.

In [5]:
df["Melhor Filme"] = df["Melhor Filme"].map({
    True: "Sim",
    False: "Não"
})

display(df)

     Ano                Filme  Indicações  Prêmios Melhor Filme
0   2010  Alice in Wonderland           3        2          Não
1   2010           Black Swan           5        1          Não
2   2010          God of Love           1        1          Não
3   2010    In a Better World           1        1          Não
4   2010            Inception           8        4          Não
..   ...                  ...         ...      ...          ...
82  2015          Stutterer             1        1          Não
83  2015      The Big Short             5        1          Não
84  2015      The Danish Girl           4        1          Não
85  2015  The Hateful Eight             2        1          Não
86  2015      The Revenant             12        3          Não

[87 rows x 5 columns]

## Etapa 6 — Verificar a quantidade de filmes por ano

Esta etapa é opcional, mas ajuda a conferir se os dados de todos os anos foram incluídos na tabela.

In [6]:
resumo = (
    df.groupby("Ano")
      .size()
      .reset_index(name="Quantidade de filmes")
)

display(resumo)

print("Total geral:", len(df))

    Ano  Quantidade de filmes
0  2010                    13
1  2011                    15
2  2012                    15
3  2013                    12
4  2014                    16
5  2015                    16

Total geral: 87

## Etapa 7 — Salvar os dados em Excel

Todos os anos serão armazenados em **uma única planilha**.

In [7]:
nome_arquivo = "oscar_2010_2015.xlsx"

df.to_excel(
    nome_arquivo,
    index=False,
    engine="openpyxl"
)

print(f"Arquivo criado com sucesso: {nome_arquivo}")

Arquivo criado com sucesso: oscar_2010_2015.xlsx

## Etapa 8 — Baixar o arquivo

Ao executar a célula abaixo no Google Colab, o arquivo Excel será baixado para o computador.

In [8]:
files.download("oscar_2010_2015.xlsx")